"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/browser";

type Role = "admin" | "manager" | "sales" | "support" | "viewer";
type Contact = { id:string; first_name:string; last_name:string; phone:string|null; email:string|null; status:string; sales_stage:string; source:string|null };
type Permission = { role:Role; module:string; can_read:boolean; can_create:boolean; can_update:boolean; can_delete:boolean };
type Rule = { id:string; name:string; event_type:string; condition_stage:string|null; action_type:string; is_active:boolean };
type Integration = { id:string; provider:string; name:string; is_enabled:boolean };

const db = createClient();
const stages:Record<string,string> = {new:"جدید",contacted:"تماس گرفته شد",qualified:"واجد شرایط",proposal:"پیشنهاد",won:"برنده",lost:"از دست رفته"};
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(Math.round(n));

export function CrmGrowthCenter(){
 const [tab,setTab]=useState("overview"),[role,setRole]=useState<Role|null>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 const [contacts,setContacts]=useState<Contact[]>([]),[rules,setRules]=useState<Rule[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[integrations,setIntegrations]=useState<Integration[]>([]);
 const [calendar,setCalendar]=useState<{id:string;title:string;due_at:string;kind:string;status:string}[]>([]);
 const [forecast,setForecast]=useState<{stage:string;count:number;value:number}[]>([]),[collected,setCollected]=useState(0),[pending,setPending]=useState(0);
 const [ruleName,setRuleName]=useState("پیگیری سرنخ جدید"),[ruleStage,setRuleStage]=useState("new"),[ruleDays,setRuleDays]=useState("1"),[ruleAction,setRuleAction]=useState("create_followup");

 async function load(){
  setLoading(true);
  const [{data:u},{data:r},{data:p},{data:i},{data:c},{data:f},{data:t},{data:regs},{data:pay}] = await Promise.all([
   db.auth.getUser(),
   db.from("automation_rules").select("id,name,event_type,condition_stage,action_type,is_active").order("created_at",{ascending:false}),
   db.from("role_permissions").select("role,module,can_read,can_create,can_update,can_delete").order("role"),
   db.from("integrations").select("id,provider,name,is_enabled").order("provider"),
   db.from("contacts").select("id,first_name,last_name,phone,email,status,sales_stage,source").order("created_at",{ascending:false}).limit(5000),
   db.from("follow_ups").select("id,title,due_at,status").neq("status","cancelled").order("due_at").limit(100),
   db.from("tasks").select("id,title,due_at,status").neq("status","cancelled").not("due_at","is",null).order("due_at").limit(100),
   db.from("registrations").select("id,status,course:courses(price)").in("status",["pending","active","completed"]).limit(1000),
   db.from("payments").select("amount,status").neq("status","cancelled").limit(5000)
  ]);
  if(u.user){const {data:pr}=await db.from("profiles").select("role").eq("id",u.user.id).maybeSingle();setRole((pr?.role as Role)||null)}
  setContacts((c||[]) as Contact[]);setRules((r||[]) as Rule[]);setPermissions((p||[]) as Permission[]);setIntegrations((i||[]) as Integration[]);
  setCalendar([
   ...((f||[]) as {id:string;title:string;due_at:string;status:string}[]).map(x=>({...x,kind:"پیگیری"})),
   ...((t||[]) as {id:string;title:string;due_at:string;status:string}[]).map(x=>({...x,kind:"وظیفه"})),
  ].sort((a,b)=>+new Date(a.due_at)-+new Date(b.due_at)).slice(0,60));
  const payments=(pay||[]) as {amount:number|string;status:string}[];
  setCollected(payments.filter(x=>["paid","partial"].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0));
  setPending(payments.filter(x=>["pending","partial"].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0));
  const map=new Map<string,{count:number;value:number}>();
  ((regs||[]) as {status:string;course?:{price?:number}|null}[]).forEach(x=>{const row=map.get(x.status)||{count:0,value:0};row.count++;row.value+=Number(x.course?.price||0);map.set(x.status,row)});
  const counts=new Map<string,number>();(c||[]).forEach((x:{sales_stage:string})=>counts.set(x.sales_stage,(counts.get(x.sales_stage)||0)+1));
  setForecast(Object.keys(stages).map(stage=>({stage,count:counts.get(stage)||map.get(stage)?.count||0,value:map.get(stage)?.value||0})));
  setLoading(false);
 }
 useEffect(()=>{load()},[]);
 const admin=role==="admin", manager=admin||role==="manager";
 const weighted=useMemo(()=>forecast.reduce((s,x)=>s+x.value*(({new:.1,contacted:.2,qualified:.4,proposal:.7,won:1,lost:0} as Record<string,number>)[x.stage]||0),0),[forecast]);
 const duplicateGroups=useMemo(()=>{const m=new Map<string,Contact[]>();contacts.forEach(c=>[c.phone?.replace(/\D/g,"")||"",c.email?.trim().toLowerCase()||""].filter(Boolean).forEach(k=>m.set(k,[...(m.get(k)||[]),c])));return [...m.entries()].filter(([,v])=>v.length>1)},[contacts]);

 async function addRule(){if(!manager)return;const {error}=await db.from("automation_rules").insert({name:ruleName.trim(),event_type:"contact_created",condition_stage:ruleStage,action_type:ruleAction,action_config:{title:ruleName.trim(),days:Math.max(0,Number(ruleDays)||1)}});setMsg(error?.message||"قانون ساخته شد.");if(!error)load()}
 async function runRules(){if(!manager)return;const {data,error}=await db.rpc("run_contact_automations");setMsg(error?.message||`خودکارسازی اجرا شد؛ ${data||0} اقدام ایجاد شد.`);load()}
 async function merge(primary:string,dup:string){if(!admin)return;const {error}=await db.rpc("merge_contacts",{primary_id:primary,duplicate_id:dup});setMsg(error?.message||"پرونده‌ها ادغام شدند.");load()}
 async function perm(p:Permission,k:"can_read"|"can_create"|"can_update"|"can_delete"){if(!admin)return;const {error}=await db.from("role_permissions").update({[k]:!p[k],updated_at:new Date().toISOString()}).eq("role",p.role).eq("module",p.module);if(error)setMsg(error.message);else setPermissions(v=>v.map(x=>x.role===p.role&&x.module===p.module?{...x,[k]:!p[k]}:x))}
 async function toggle(i:Integration){if(!admin)return;const {error}=await db.from("integrations").update({is_enabled:!i.is_enabled}).eq("id",i.id);setMsg(error?.message||`${i.name} به‌روزرسانی شد.`);if(!error)setIntegrations(v=>v.map(x=>x.id===i.id?{...x,is_enabled:!i.is_enabled}:x))}
 function csvEscape(v:unknown){return `"${String(v??"").replaceAll('"','""')}"`}
 function exportCsv(){const head=["first_name","last_name","phone","email","status","sales_stage","source"],csv="\ufeff"+[head.join(","),...contacts.map(c=>head.map(k=>csvEscape(c[k as keyof Contact])).join(","))].join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`tasnim-crm-${Date.now()}.csv`;a.click();URL.revokeObjectURL(a.href);setMsg("خروجی Excel-compatible آماده شد.")}
 async function importCsv(file:File){const lines=(await file.text()).split(/\r?\n/).filter(Boolean);if(lines.length<2){setMsg("فایل خالی است.");return}const fields=(lines[0]||"").split(",").map(x=>x.trim().replace(/^"|"$/g,""));const rows=lines.slice(1).map(line=>line.split(",")).map(v=>Object.fromEntries(fields.map((f,n)=>[f,(v[n]||"").replace(/^"|"$/g,"")]))).filter(x=>x.first_name?.trim());const payload=rows.map(x=>({first_name:String(x.first_name).trim(),last_name:String(x.last_name||"").trim(),phone:String(x.phone||"").trim()||null,email:String(x.email||"").trim()||null,status:["lead","active","inactive","customer"].includes(x.status)?x.status:"lead",sales_stage:["new","contacted","qualified","proposal","won","lost"].includes(x.sales_stage)?x.sales_stage:"new",source:String(x.source||"").trim()||null}));for(let n=0;n<payload.length;n+=100){const {error}=await db.from("contacts").insert(payload.slice(n,n+100));if(error){setMsg(error.message);break}}setMsg(`${payload.length} مخاطب پردازش شد.`);load()}
 const insight=`${forecast.find(x=>x.stage==="proposal")?.count||0} پرونده در مرحله پیشنهاد است. ارزش وزنی قیف ${money(weighted)} تومان و دریافتی ثبت‌شده ${money(collected)} تومان است. تمرکز پیشنهادی روی پیگیری پیشنهادهای باز و پرونده‌های نزدیک به برد است.`;
 if(loading)return <div className="rounded-3xl border border-slate-200 bg-white p-8 text-sm font-bold text-slate-500">در حال بارگذاری مرکز امکانات…</div>;
 const tabs=[["overview","نمای کلی"],["automation","خودکارسازی"],["reports","گزارش و پیش‌بینی"],["calendar","تقویم"],["data","ورود/خروجی"],["duplicates","تکراری‌ها"],["access","دسترسی‌ها"],["integrations","اتصالات و AI"]];
 return <div className="space-y-6">
  <div className="rounded-[2rem] bg-slate-950 p-6 text-white shadow-xl"><p className="text-xs font-black tracking-[.2em] text-amber-400">CRM GROWTH CENTER</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">مرکز امکانات حرفه‌ای CRM</h1><p className="mt-2 text-sm leading-7 text-slate-300">خودکارسازی، گزارش فروش، دسترسی ریزدانه، تقویم، Excel، کنترل تکراری‌ها، Forecast و اتصالات.</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["مخاطب",contacts.length],["تکراری",duplicateGroups.length],["قیف وزنی",weighted],["دریافتی",collected]].map(([a,b])=><div key={a as string} className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-slate-400">{a}</p><p className="mt-1 text-lg font-black">{money(Number(b))}</p></div>)}</div></div>
  <div className="flex gap-2 overflow-x-auto">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-2xl px-4 py-2.5 text-sm font-black ${tab===id?"bg-slate-950 text-white":"bg-slate-50 text-slate-500"}`}>{label}</button>)}</div>
  {msg&&<div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-900">{msg}</div>}
  {tab==="overview"&&<div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">نمای مدیریتی</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{forecast.map(x=><div key={x.stage} className="rounded-2xl bg-slate-50 p-4"><p className="text-sm font-bold">{stages[x.stage]}</p><p className="mt-2 text-xl font-black">{money(x.value)} تومان</p><p className="mt-1 text-xs text-slate-500">{money(x.count)} پرونده</p></div>)}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">دستیار هوشمند داخلی</h2><p className="mt-3 rounded-2xl bg-slate-950 p-5 text-sm leading-8 text-slate-200">{insight}</p><p className="mt-3 text-xs leading-6 text-slate-500">نسخه فعلی بدون ارسال اطلاعات به سرویس بیرونی است؛ اتصال مدل بیرونی فقط از سمت سرور انجام می‌شود.</p></section></div>}
  {tab==="automation"&&<div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">قانون جدید</h2><div className="mt-4 space-y-3"><input value={ruleName} onChange={e=>setRuleName(e.target.value)} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="نام قانون"/><select value={ruleStage} onChange={e=>setRuleStage(e.target.value)} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm">{Object.entries(stages).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={ruleAction} onChange={e=>setRuleAction(e.target.value)} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm"><option value="create_followup">ایجاد پیگیری</option><option value="create_task">ایجاد وظیفه</option></select><input type="number" min="0" value={ruleDays} onChange={e=>setRuleDays(e.target.value)} className="w-full rounded-2xl border border-slate-200 px-4 py-3 text-sm"/><button disabled={!manager} onClick={addRule} className="w-full rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white disabled:opacity-40">ذخیره</button><button disabled={!manager} onClick={runRules} className="w-full rounded-2xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-black text-amber-900 disabled:opacity-40">اجرای خودکارسازی‌ها</button></div></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">قوانین</h2><div className="mt-4 space-y-3">{rules.map(r=><div key={r.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-black">{r.name}</p><p className="mt-1 text-xs text-slate-500">{r.action_type==="create_followup"?"ایجاد پیگیری":"ایجاد وظیفه"} · شرط: {r.condition_stage?stages[r.condition_stage]:"همه"} · {r.is_active?"فعال":"خاموش"}</p></div>)}</div></section></div>}
  {tab==="reports"&&<section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Forecast و گزارش فروش</h2><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs text-slate-500">قیف وزنی</p><p className="mt-2 text-2xl font-black">{money(weighted)} تومان</p></div><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs text-slate-500">در انتظار/جزئی</p><p className="mt-2 text-2xl font-black">{money(pending)} تومان</p></div><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs text-slate-500">دریافتی</p><p className="mt-2 text-2xl font-black">{money(collected)} تومان</p></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b text-xs text-slate-400"><th className="px-3 py-3">مرحله</th><th>پرونده</th><th>ارزش</th><th>ضریب</th><th>وزنی</th></tr></thead><tbody>{forecast.map(x=>{const w=({new:.1,contacted:.2,qualified:.4,proposal:.7,won:1,lost:0} as Record<string,number>)[x.stage]||0;return <tr key={x.stage} className="border-b border-slate-100"><td className="px-3 py-3 font-black">{stages[x.stage]}</td><td>{x.count}</td><td>{money(x.value)}</td><td>{w*100}٪</td><td className="font-black">{money(x.value*w)}</td></tr>})}</tbody></table></div></section>}
  {tab==="calendar"&&<section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">تقویم عملیاتی</h2><p className="mt-1 text-sm text-slate-500">پیگیری‌ها و وظایف براساس سررسید.</p><div className="mt-4 space-y-3">{calendar.map(x=><div key={`${x.kind}-${x.id}`} className="flex flex-col gap-2 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:justify-between"><div><p className="font-black">{x.kind}: {x.title}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x.due_at))}</p></div><span className="text-xs font-bold">{x.status}</span></div>)}</div></section>}
  {tab==="data"&&<div className="grid gap-5 md:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">خروجی Excel / CSV</h2><p className="mt-2 text-sm text-slate-500">فایل UTF-8 و سازگار با Excel.</p><button onClick={exportCsv} className="mt-5 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white">دریافت خروجی</button></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">ورود بانک مخاطبان</h2><p className="mt-2 text-sm text-slate-500">ستون‌ها: first_name, last_name, phone, email, status, sales_stage, source</p><label className="mt-5 flex cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-8 text-sm font-black"><input className="hidden" type="file" accept=".csv" disabled={!role||role==="viewer"} onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/>انتخاب CSV</label></section></div>}
  {tab==="duplicates"&&<section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">تشخیص و ادغام تکراری‌ها</h2><div className="mt-5 space-y-4">{duplicateGroups.map(([key,rows])=><div key={key} className="rounded-2xl bg-amber-50/60 p-4"><p className="text-xs font-black text-amber-700">کلید: {key}</p>{rows.map((c,n)=><div key={c.id} className="mt-2 flex flex-col gap-2 rounded-xl bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><span className="font-black">{c.first_name} {c.last_name} · {c.phone||c.email}</span>{n>0&&<button disabled={!admin} onClick={()=>merge(rows[0].id,c.id)} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700 disabled:opacity-40">ادغام با پرونده اول</button>}</div>)}</div>)}{duplicateGroups.length===0&&<p className="py-10 text-center text-sm text-slate-400">تکراری آشکاری پیدا نشد.</p>}</div></section>}
  {tab==="access"&&<section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">دسترسی ریزدانه</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-xs text-slate-400"><th className="p-3">نقش</th><th>ماژول</th><th>مشاهده</th><th>ایجاد</th><th>ویرایش</th><th>حذف</th></tr></thead><tbody>{permissions.map(p=><tr key={`${p.role}-${p.module}`} className="border-b border-slate-100"><td className="p-3 font-black">{p.role}</td><td>{p.module}</td>{(["can_read","can_create","can_update","can_delete"] as const).map(k=><td key={k}><button disabled={!admin} onClick={()=>perm(p,k)} className={`rounded-full px-3 py-1 text-xs font-black ${p[k]?"bg-slate-950 text-white":"bg-slate-100 text-slate-400"}`}>{p[k]?"فعال":"خاموش"}</button></td>)}</tr>)}</tbody></table></div></section>}
  {tab==="integrations"&&<div className="grid gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">اتصالات</h2><p className="mt-2 text-sm text-slate-500">تقویم، پیام‌رسان و AI به‌عنوان اتصال مستقل مدیریت می‌شوند.</p><div className="mt-4 space-y-3">{integrations.map(i=><div key={i.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="font-black">{i.name}</p><p className="text-xs text-slate-500">{i.provider}</p></div><button disabled={!admin} onClick={()=>toggle(i)} className={`rounded-xl px-3 py-2 text-xs font-black ${i.is_enabled?"bg-slate-950 text-white":"bg-white text-slate-500"}`}>{i.is_enabled?"فعال":"خاموش"}</button></div>)}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">AI آماده اتصال</h2><p className="mt-2 text-sm leading-7 text-slate-500">دستیار داخلی الان تحلیل عددی و عملیاتی دارد. برای مدل بیرونی، API Key باید فقط در Secret/Environment سرور قرار بگیرد و هرگز داخل کد یا دیتابیس عمومی ذخیره نشود.</p><div className="mt-5 rounded-2xl bg-slate-950 p-5 text-sm leading-8 text-slate-200">{insight}</div></section></div>}
 </div>
}
