"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/browser";

type Contact={first_name:string;last_name:string;phone:string|null;email:string|null;birth_date:string|null;status:string;source:string|null;notes:string|null};

export default function EditContactPage(){
 const router=useRouter(); const params=useParams<{id:string}>(); const id=params.id;
 const [data,setData]=useState<Contact|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{let active=true; createClient().from("contacts").select("first_name,last_name,phone,email,birth_date,status,source,notes").eq("id",id).maybeSingle().then(({data,error})=>{if(!active)return;if(error||!data){setError("پرونده مخاطب پیدا نشد.")}else{setData(data as Contact)}setLoading(false)});return()=>{active=false}},[id]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);const {error}=await createClient().from("contacts").update({first_name:String(f.get("first_name")||"").trim(),last_name:String(f.get("last_name")||"").trim(),phone:String(f.get("phone")||"").trim()||null,email:String(f.get("email")||"").trim()||null,birth_date:f.get("birth_date")||null,status:f.get("status"),source:String(f.get("source")||"").trim()||null,notes:String(f.get("notes")||"").trim()||null}).eq("id",id);if(error){setError("ویرایش مخاطب انجام نشد. ممکن است دسترسی کافی نداشته باشید.");setSaving(false);return}router.push(`/contacts/${id}`);router.refresh()}
 if(loading)return <div className="rounded-3xl bg-white p-8 text-sm text-slate-400">در حال بارگذاری...</div>;
 if(!data)return <div className="rounded-3xl bg-white p-8 text-sm text-red-600">{error}</div>;
 return <div className="max-w-3xl"><div className="mb-7"><p className="text-xs font-black text-amber-600">TASNIM ROYAL CRM</p><h1 className="mt-1 text-2xl font-black">ویرایش مخاطب</h1><p className="mt-2 text-sm text-slate-500">اصلاح اطلاعات و وضعیت پرونده</p></div><form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-4 md:grid-cols-2">{[["first_name","نام"],["last_name","نام خانوادگی"],["phone","شماره تماس"],["email","ایمیل"]].map(([name,label])=><label key={name}><span className="mb-2 block text-sm font-bold">{label}</span><input name={name} defaultValue={String(data[name as keyof Contact]||"")} required={name==="first_name"||name==="last_name"} className="w-full rounded-2xl border px-4 py-3"/></label>)}<label><span className="mb-2 block text-sm font-bold">تاریخ تولد</span><input name="birth_date" type="date" defaultValue={data.birth_date||""} className="w-full rounded-2xl border px-4 py-3"/></label><label><span className="mb-2 block text-sm font-bold">وضعیت</span><select name="status" defaultValue={data.status} className="w-full rounded-2xl border bg-white px-4 py-3"><option value="lead">سرنخ</option><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="customer">مشتری</option></select></label></div><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">منبع آشنایی</span><input name="source" defaultValue={data.source||""} className="w-full rounded-2xl border px-4 py-3"/></label><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">یادداشت</span><textarea name="notes" defaultValue={data.notes||""} rows={4} className="w-full rounded-2xl border px-4 py-3"/></label>{error&&<p className="mt-4 text-sm font-bold text-red-600">{error}</p>}<div className="mt-6 flex gap-3"><button type="button" onClick={()=>router.back()} className="rounded-2xl border px-5 py-3 font-bold">انصراف</button><button disabled={saving} className="rounded-2xl bg-slate-950 px-6 py-3 font-black text-white disabled:opacity-60">{saving?"در حال ذخیره...":"ذخیره تغییرات"}</button></div></form></div>
}
